name : Palywright Tests

on : 
  push : branches : [main]

jobs :
  test :
  runs-on: ubuntu-latest
  steps :
  -name : Checkout Repository
   uses : actions/checkout@v2

  -name : setup python
    uses : actions/setup-python@v2
    with :
      python-version : '3.12'
  -name : install Playwright
    run : |
      pip install pytest-playwright
  -name : install Browsers
    run : |
      playwright install
  -name : Install Reporting Tool
    run : |
      pip install pytest-html
  -name : Run Playwright Tests
    run : pytest tests/